apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: kafka  # Deploy in the same namespace
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: "my-cluster-kafka-bootstrap:9092"  # Replace with your Kafka bootstrap service
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 15
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 15
            timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: kafka
spec:
  type: LoadBalancer  # Use LoadBalancer, NodePort, or ClusterIP depending on your environment
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: kafdrop
