apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/henneberger/sqrl-k8s/
  claimRef:
    namespace: default
    name: local-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  storageClassName: manual    # Added storageClassName
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: linux-pod
spec:
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: local-pvc
  containers:
    - name: basic-linux
      image: ubuntu
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - mountPath: /mnt/host
          name: my-volume
