apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: 'datasqrl/sqrl-server:latest'
          workingDir: /opt/sqrl
          command: ["java", "-jar", "vertx-server.jar"]
          env:
            - name: PGHOST
              value: "database-rw"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "datasqrl"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: "postgres"
            - name: PROPERTIES_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: graphiql/
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
          imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888