apiVersion: v1
kind: Service
metadata:
  name: vertx-server
  labels:
    app: vertx-server
spec:
  selector:
    app: vertx-server
  ports:
    - protocol: TCP
      port: {{ .Values.vertxServer.servicePort }}
      targetPort: {{ .Values.vertxServer.servicePort }}
  type: LoadBalancer
