apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgres.postgresClusterName }}
  namespace: {{ .Values.kafka.namespace }}
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: standard
  postgresql:
    version: "14"
  bootstrap:
    initdb:
      options: "--data-checksums"
  superUserSecret:
    name: {{ .Values.postgres.postgresClusterName }}-secret
  databases:
      - name: appdb
  users:
    - name: appuser
      databases:
        - appdb
  monitor:
    enabled: true
