apiVersion: v1
kind: Service
metadata:
  name: flink
  labels:
    app: flink
spec:
  selector:
    app: flink
  ports:
    - protocol: TCP
      port: {{ .Values.flink.servicePort }}
      targetPort: {{ .Values.flink.servicePort }}
